server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: admin
      enable-csrf: false

feign:
  user-service:
    url: localhost:8080/user

logging.level.org.springframework.web: INFO
