server:
  port: 8081

spring:
  application:
    name:
      auth-service
  security:
    user:
      name: admin
      password: admin
      enable-csrf: false

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf
  life-time: 1800000

feign:
  user-service:
    url: localhost:8080/user

logging.level.org.springframework.web: INFO
